version: '3.8'

services:
  oci-gateway:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    image: ghcr.io/${GITHUB_REPOSITORY:-local/oci-gateway}:latest
    env_file:
      - ${ENV_FILE:-gateway.env}
    environment:
      # OCI configuration from secrets
      TF_VAR_tenancy_ocid: ${OCI_TENANCY_OCID}
      TF_VAR_user_ocid: ${OCI_USER_OCID}
      TF_VAR_fingerprint: ${OCI_FINGERPRINT}
      TF_VAR_region: ${OCI_REGION}
      TF_VAR_compartment_id: ${OCI_COMPARTMENT_ID}
      TF_VAR_availability_domain: ${OCI_AVAILABILITY_DOMAIN}
      # XDG paths inside container
      XDG_DATA_HOME: /data
      XDG_CONFIG_HOME: /config
      XDG_STATE_HOME: /state
      TIN_NAMESPACE: ${TIN_NAMESPACE:-dynamicalsystem}
      TIN_SERVICE_NAME: ${TIN_SERVICE_NAME:-gateway}
      # Legacy mode flag
      USE_RESOURCE_MANAGER: ${USE_RESOURCE_MANAGER:-false}
      # Secret paths inside container
      OCI_PRIVATE_KEY_PATH: /secrets/oci_api_key.pem
      OCI_SSH_PUBLIC_KEY_PATH: /secrets/id_oci.pub
    volumes:
      # Mount XDG directories - paths come from .env file, no defaults
      - ${XDG_DATA_HOME}/${TIN_NAMESPACE}/${TIN_SERVICE_NAME}:/data:Z
      - ${XDG_CONFIG_HOME}/${TIN_NAMESPACE}/${TIN_SERVICE_NAME}:/config:Z
      - ${XDG_STATE_HOME}/${TIN_NAMESPACE}/${TIN_SERVICE_NAME}:/state:Z
      
      # Mount secrets as read-only
      - ${XDG_DATA_HOME}/${TIN_NAMESPACE}/${TIN_SERVICE_NAME}/oci/oci_api_key.pem:/secrets/oci_api_key.pem:ro
      - ${XDG_CONFIG_HOME}/${TIN_NAMESPACE}/${TIN_SERVICE_NAME}/ssh/id_oci.pub:/secrets/id_oci.pub:ro
    command: ${USE_RESOURCE_MANAGER:+uv run main.py}
    restart: unless-stopped
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}