# Tinsnip Integration Override
# This file applies tinsnip-specific requirements to the base docker-compose.yml
# Used when deploying via tinsnip infrastructure

services:
  gateway:
    # Container naming convention
    container_name: ${TIN_SERVICE_NAME:-gateway}-${TIN_SERVICE_ENVIRONMENT:-prod}
    
    # Use tinsnip service UID
    user: "${TIN_SERVICE_UID}:${TIN_SERVICE_UID}"
    
    # Add tinsnip service metadata
    environment:
      TIN_SERVICE_NAME: ${TIN_SERVICE_NAME:-gateway}
      TIN_SERVICE_ENVIRONMENT: ${TIN_SERVICE_ENVIRONMENT:-prod} 
      TIN_SERVICE_UID: ${TIN_SERVICE_UID}
    
    # Gateway doesn't need tinsnip_network - it provisions external OCI instances
    # Remove network configuration to use default bridge network